#!/usr/bin/env python3
"""
Test script to verify all RL environment descriptions are unique and relevant
"""
import sys
import os
sys.path.insert(0, '.')

from portal.environment_registry import list_all_environments

def test_descriptions():
    """Test that all environments have unique, relevant descriptions"""
    envs = list_all_environments()
    
    print(f"Testing {len(envs)} environments...")
    print("=" * 80)
    
    # Track descriptions to check for uniqueness
    descriptions = {}
    issues = []
    
    for env in envs:
        env_name = env['name']
        category = env.get('category', 'unknown')
        workflow = env.get('workflow', 'N/A')
        system = env.get('system', 'N/A')
        
        # Check if description exists (will be generated by frontend)
        # For now, we'll check the structure
        description_key = f"{env_name}_description"
        
        # Check for basic metadata
        if not category:
            issues.append(f"❌ {env_name}: Missing category")
        if not workflow or workflow == 'N/A':
            issues.append(f"⚠️  {env_name}: Missing or generic workflow")
        if not system or system == 'Multiple':
            # This is OK for cross-workflow environments
            if category != 'cross_workflow':
                issues.append(f"⚠️  {env_name}: Generic system assignment")
        
        # Store for uniqueness check (we'll check in frontend)
        descriptions[env_name] = {
            'category': category,
            'workflow': workflow,
            'system': system
        }
    
    # Check category distribution
    categories = {}
    for env_name, data in descriptions.items():
        cat = data['category']
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\n📊 Category Distribution:")
    for cat, count in sorted(categories.items()):
        print(f"   {cat}: {count} environments")
    
    # Check workflow distribution
    workflows = {}
    for env_name, data in descriptions.items():
        wf = data['workflow']
        workflows[wf] = workflows.get(wf, 0) + 1
    
    print("\n📊 Workflow Distribution:")
    for wf, count in sorted(workflows.items()):
        print(f"   {wf}: {count} environments")
    
    # Report issues
    if issues:
        print(f"\n⚠️  Found {len(issues)} potential issues:")
        for issue in issues[:20]:  # Show first 20
            print(f"   {issue}")
        if len(issues) > 20:
            print(f"   ... and {len(issues) - 20} more")
    else:
        print("\n✅ No issues found!")
    
    print(f"\n✅ Total environments tested: {len(envs)}")
    print(f"✅ Categories: {len(categories)}")
    print(f"✅ Workflows: {len(workflows)}")
    
    return len(issues) == 0

if __name__ == '__main__':
    success = test_descriptions()
    sys.exit(0 if success else 1)

